Repository DuendeSoftware/docs.duendesoftware.com, pull requests merged in 2025-06, with the labels that each got.

#748 Update description for `FeaturesUsed` in LicenseUsageSummary documentation
  src/content/docs/identityserver/reference/models/license-usage-summary.md
Labels: bug, documentation

#760 Improve documentation formatting for Forwarded Headers middleware usage
  src/content/docs/identityserver/deployment.md
Labels: documentation

#785 Update Introspection Endpoint docs with RFC 9701
  src/content/docs/identityserver/reference/endpoints/introspection.md
Labels: documentation

#767 Refine IdentityServer template documentation and examples
  src/content/docs/identityserver/overview/packaging.mdx
Labels: documentation

#797 Updated reference to global configuration setting with the correct name
  src/content/docs/identityserver/reference/dcr/models.md
  src/content/docs/identityserver/reference/models/client.md
Labels: documentation

#799 Clarify what RequireResourceIndicator actually does
  src/content/docs/identityserver/fundamentals/resources/isolation.md
Labels: documentation, enhancement

#791 Add FAPI 2.0 documentation for Duende IdentityServer
  src/content/docs/identityserver/tokens/fapi-2-0-specification.md
Labels: documentation

#804 Add Client Auth Jwt Type
  src/content/docs/identitymodel/utils/constants.md
Labels: documentation
