Repository DuendeSoftware/docs.duendesoftware.com, pull requests merged in 2025-02, with the labels that each got.

#582 Add canonical link handling to custom headers
  IdentityServer/v5/docs/themes/hugo-theme-learn/layouts/partials/canonical.html
  IdentityServer/v5/docs/themes/hugo-theme-learn/layouts/partials/custom-header.html
  IdentityServer/v6/docs/themes/hugo-theme-learn/layouts/partials/canonical.html
  IdentityServer/v6/docs/themes/hugo-theme-learn/layouts/partials/custom-header.html
  IdentityServer/v7/docs/themes/hugo-theme-learn/layouts/partials/canonical.html
  IdentityServer/v7/docs/themes/hugo-theme-learn/layouts/partials/custom-header.html
Labels: documentation

#581 Replace deprecated breadcrumb metadata with Schema.org
  IdentityServer/v5/docs/themes/hugo-theme-learn/layouts/partials/header.html
  IdentityServer/v6/docs/themes/hugo-theme-learn/layouts/partials/header.html
  IdentityServer/v7/docs/themes/hugo-theme-learn/layouts/partials/header.html
Labels: bug, documentation

#586 Update license page
  IdentityServer/v7/docs/content/fundamentals/license_key.md
Labels: enhancement

#585 Update breadcrumb structure for improved schema compliance
  FOSS/themes/hugo-theme-learn/layouts/partials/header.html
  IdentityServer/v5/docs/themes/hugo-theme-learn/layouts/partials/header.html
  IdentityServer/v6/docs/themes/hugo-theme-learn/layouts/partials/header.html
  IdentityServer/v7/docs/themes/hugo-theme-learn/layouts/partials/header.html
Labels: bug, enhancement

#588 Refactor breadcrumb markup for schema.org compliance
  FOSS/themes/hugo-theme-learn/layouts/partials/header.html
  IdentityServer/v5/docs/themes/hugo-theme-learn/layouts/partials/header.html
  IdentityServer/v6/docs/themes/hugo-theme-learn/layouts/partials/header.html
  IdentityServer/v7/docs/themes/hugo-theme-learn/layouts/partials/header.html
Labels: bug

#594 Add note on X.509 certificate expiration in documentation
  IdentityServer/v7/docs/content/fundamentals/keys/automatic_key_management.md
  IdentityServer/v7/docs/content/reference/options.md
Labels: enhancement
