Repository DuendeSoftware/docs.duendesoftware.com, pull requests merged in 2025-07, with the labels that each got.

#803 Updated the upgrade to 7.3 docs with a breaking change concerning client_secret_jwt
  src/content/docs/identityserver/tokens/client-authentication.md
  src/content/docs/identityserver/upgrades/v7_2-to-v7_3.md
Labels: documentation

#812 Add pagefind-ignore attribute and update Banner styling
  src/components/Banner.astro
Labels: bug, documentation

#819 Change font-family to Helvetica and move away from Roboto. It doesn't seem to load for some folks.
  src/content/docs/identityserver/ui/images/ciba.svg
  src/content/docs/identityserver/ui/images/federation.svg
  src/content/docs/identityserver/ui/images/host.svg
  src/content/docs/identityserver/ui/images/signin_flow.svg
Labels: bug

#821 Upgrade dependencies and standardize code formatting
  package-lock.json
  package.json
  patches/astro+5.12.1.patch
  src/content/docs/identityserver/aspnet-identity/index.md
Labels: enhancement

#820 BFF V4 docs
  src/content/docs/accesstokenmanagement/advanced/client-credentials.mdx
  src/content/docs/bff/architecture/index.md
  src/content/docs/bff/architecture/multi-frontend.md
  src/content/docs/bff/architecture/ui-hosting.md
  src/content/docs/bff/extensibility/http-forwarder.md
  src/content/docs/bff/extensibility/management/back-channel-logout.md
  src/content/docs/bff/extensibility/management/diagnostics.md
  src/content/docs/bff/extensibility/management/index.md
  src/content/docs/bff/extensibility/management/login.md
  src/content/docs/bff/extensibility/management/logout.md
  src/content/docs/bff/extensibility/management/silent-login-callback.md
  src/content/docs/bff/extensibility/management/silent-login.md
  src/content/docs/bff/extensibility/management/user.md
  src/content/docs/bff/extensibility/tokens.md
  src/content/docs/bff/fundamentals/apis/_meta.yml
  src/content/docs/bff/fundamentals/apis/index.md
  src/content/docs/bff/fundamentals/apis/local.mdx
  src/content/docs/bff/fundamentals/apis/remote.mdx
  src/content/docs/bff/fundamentals/blazor/_meta.yml
  src/content/docs/bff/fundamentals/blazor/rendering-modes.md
  src/content/docs/bff/fundamentals/multi-frontend/_meta.yml
  src/content/docs/bff/fundamentals/multi-frontend/configuration.mdx
  src/content/docs/bff/fundamentals/multi-frontend/index.mdx
  src/content/docs/bff/fundamentals/options.md
  src/content/docs/bff/fundamentals/session/_meta.yml
  src/content/docs/bff/fundamentals/session/handlers.mdx
  src/content/docs/bff/fundamentals/session/server-side-sessions.mdx
  src/content/docs/bff/fundamentals/tokens.md
  src/content/docs/bff/getting-started/blazor.mdx
  src/content/docs/bff/getting-started/multi-frontend.mdx
  src/content/docs/bff/getting-started/single-frontend.mdx
  src/content/docs/bff/images/bff-multi-frontend.svg
  src/content/docs/bff/index.mdx
  src/content/docs/bff/upgrading/bff-v3-to-v4.md
  src/content/docs/identityserver/quickstarts/7-blazor.mdx
  src/content/docs/identityserver/quickstarts/javascript-clients/js-with-backend.mdx
  src/content/docs/identityserver/reference/dcr/options.md
Labels: documentation

#825 Replaced with correct interface
  src/content/docs/identityserver/ui/consent.md
Labels: documentation
